### ISSUE TITLE
WC_Payments_Account->get_fees call crashes wp-admin upon install

### ISSUE THREAD

**Issue by jmarshall9120** [Automattic/woocommerce-payments#1162]
When clicking 'activate' on WooCommerce Payments in the 'plugins' -> 'installed' portion of the CMS, it crashes the entire CMS immediately.  Afterward the entire CMS shows the error message below, making the site useless until I ftp in and manually sudo -r rm the plugin directory.   I'm not sure why this is even loaded on the basic wp-admin page, causing and error but it is. 

```
Error message: 
Fatal error: Uncaught WCPay\Exceptions\API_Exception: Error: Sorry, you cannot access this resource. in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php:992 Stack trace: #0 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(894): WC_Payments_API_Client->extract_response_body(Array) #1 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php(620): WC_Payments_API_Client->request(Array, 'accounts', 'GET') #2 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php(532): WC_Payments_API_Client->get_account_data() #3 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/class-wc-payments-account.php(186): WC_Payments_Account->get_cached_account_data() #4 /opt/bitnami/apps/wordpress/htdocs/wp-content/plugin in /opt/bitnami/apps/wordpress/htdocs/wp-content/plugins/woocommerce-payments/includes/wc-payment-api/class-wc-payments-api-client.php on line 992
```

Code causing the expection:
includes/class-wc-payments-account.php line 186

```
/**
	 * Gets the current account fees for rendering on the settings page.
	 *
	 * @return array        Fees.
	 * @throws API_Exception Bubbles up from get_cached_account_data.
	 */
	public function get_fees() {
		$account = $this->get_cached_account_data();
		return isset( $account['fees'] ) ? $account['fees'] : [];
	}
```
Updates on workarounds tried:
1. I've upgraded wordpress and all plugins:
    a. WooCommerce: 4.8.0
    b. WooCommerce Shipping & Tax: 1.25.4
    c. Wordpress: 5.6

2. I've also done the DB updates for WooCommerce and Wordpress.
3. I've added the tag `define( 'WP_ENVIRONMENT_TYPE', 'staging' );` to my wp-config.php

Still no change.

**Comment by DanReyLop** [comment]
Hey @jmarshall9120 , thanks for opening such a detailed issue! Sorry you had this trouble, it was definitely an oversight on our part, that error slipped through our testing.

This is fixed on https://github.com/Automattic/woocommerce-payments/pull/1133 , which will be part of the next release of WooCommerce Payments. We are planning of making that release during next week (14th-18th Dec).

**Comment by jmarshall9120** [comment]
@DanReyLop - I just installed the patched version, still not working out.  I don't get the setup screen now.  

![image](https://user-images.githubusercontent.com/30184747/102564182-bec4c680-408f-11eb-94f8-3470f38135fb.png)

This is what I see when clicking payments right after install.  There seems to be know way to resolve the issue using the interface.  I'm just digging into it on the backend now.

**Comment by shendy-a8c** [comment]
@jmarshall9120 Could you confirm the version of woocommerce-payments?
You can either get it from the Installed plugin page, ie wp-admin/plugins.php of your site, or by looking at this file via FTP: [wp-content/plugins/woocommerce-payments/woocommerce-payments.php](https://github.com/Automattic/woocommerce-payments/blob/1.8.0/woocommerce-payments.php#L13)

Also, what do you see from your error log this time?

**Comment by jmarshall9120** [comment]
@shendy-a8c 
Woocommerce payments 1.8

I didn't get time to look into the error log for the server, but there is no error outputing to the screen with `WP_DEBUG == True` .  You can however see two errors in the pop-up on the bottom left corner of the screenshot I attached, but I don't think it will be too helpful.  There more user facing labels than proper stderr output.

I'm assuming there should be a standard template backing the plug in that checks for setup.  It's like it thinks my install has been configured by it really hasn't. :(

**Comment by vbelolapotkov** [comment]
@jmarshall9120 the patch we've applied prevents site crashes rather than fixes the connection issues. With new version you have a UI available - it's without data but still available. The right place to go is Payments > Settings page. However, I can guess you'll see connection error message on that page.

One thing is not clear to me though. You've mentioned issues started when WC Payments plugin was activated. Is it the first time when the plugin is installed on the site or it was on the site some time before (connected and functioning)?

**Comment by vbelolapotkov** [comment]
I also noticed from the screenshot there is Jetpack plugin installed on the site. What's the status of the Jetpack connection? Is it live and active? Anyway it's worth trying to reconnect site to Jetpack (disconnect/connect).

**Comment by jmarshall9120** [comment]
@vbelolapotkov - Eureka!  I uninstalled jetpack and it worked. Not sure what the connection between those plugins is, but I seem to be off and running. 

To answer your other question - this is a first time install.

**Comment by vbelolapotkov** [comment]
@jmarshall9120 there might be a bug in cross plugin interaction. Do you remember what was the version of Jetpack installed? Do you remember if Jetpack was disabled/unused for a long time or something like that?

**Comment by jmarshall9120** [comment]
@vbelolapotkov - 
Jetpack 9.0.2
Looks like it can be updated.
I haven't used jetpack before, I think it came installed with Bitnami.
