### ISSUE TITLE
Some orders do not have payment information and the corresponding transaction does not show order number

### ISSUE THREAD

**Issue by billrobbins** [Automattic/woocommerce-payments#3440]
### Describe the bug
We have a few reports of orders that are paid for but where no order data is saved to the order.  In Payments > Transactions, these payments don't have the order number listed.  The order number is listed in the Stripe Express dashboard.  

### To Reproduce
We have not been able to reproduce this.  It's an intermittent issue as seen in 4462946-zen and 4318150-zen.

Slack: https://a8c.slack.com/archives/CGGCLBN58/p1637596846252500

### Actual behavior
No order notes are created with payment information as expected.  The payment method does list WooCommerce Payments but nothing more.  In the transaction list and detail view, the order number is missing.  If the payment intent is loaded in the Stripe Express dashboard, the order number is listed there.

### Screenshots
![no-order-number](https://user-images.githubusercontent.com/1138631/143906488-1e072554-4bc0-481d-bf1e-2b96a457ef50.png)

![order-without-details](https://user-images.githubusercontent.com/1138631/143906509-b684ceda-7e3d-4928-b128-1f65ba377b15.png)

### Expected behavior
I expect payment information to be saved to orders and for the order number to be available in the transaction list.  

### Desktop (please complete the following information):

* OS: MacOS
* Browser: Chrome
* Version: 96.0.4664.45

### Additional context
4462946-zen 
4318150-zen
https://a8c.slack.com/archives/CGGCLBN58/p1637596846252500

**Comment by htdat** [comment]
I think this issue has the same cause as https://github.com/Automattic/woocommerce-payments/issues/3405 and it will be fixed WCPay 3.4.0 with this PR https://github.com/Automattic/woocommerce-payments/pull/3408 

@daquinons and @Automattic/sigma - can you help confirm it?

**Comment by daquinons** [comment]
@htdat I don't think this is the same cause as #3405. However it could be related to what we were trying to fix with #3118 

This intermitent behavior seems similar to what we were experiencing here p1632910703088200-slack-C01B8KNUYSW 

It could be that now, instead of getting the orders to cancel, we are setting them as paid with this webhook modified in #3118 https://github.com/Automattic/woocommerce-payments/blob/152057ca836ef80b3a8fec6589882f253df888ee/includes/admin/class-wc-rest-payments-webhook-controller.php#L268

To check that, we added the logger `Logger::debug( 'intent_id not found, using order_id to retrieve order' );`, could be interesting to see if those orders have that log line. That would mean that the webhook was triggered when the intent_id was not found in any order. Before the modification, the intent id would not be found, so the payment confirmation would never arrive and the order would be canceled (but paid in Stripe).

We thought the `intent_id` was not found because the payment confirmation would arrive earlier than it was saved (because of network congestion, etc). But if this is related to that issue, something else is not saving the intent metadata, having these orders set as paid but with nothing else in them.

**Comment by htdat** [comment]
Thanks @daquinons. As discussed on Slack, this issue will be a part of Sigma sprints.

**Comment by daquinons** [comment]
We are also going to see if the partial revert of #3408 helps with this issue once is merged, so after 3.4 is released would be great to get other cases noted if they still exist @billrobbins

**Comment by tijosh** [comment]
Reported in 33000555-hc / 4569609-zen

Also a manually created order in this case.

**Comment by darcie** [comment]
4632339-zen and 4617247-zen appear to show the same issue.

**Comment by slash1andy** [comment]
4640679-zen also showing this

**Comment by aheckler** [comment]
4648135-zen and 4614502-zen are this as well.

**Comment by aheckler** [comment]
cc @luizreis here since this seems sort of similar to https://github.com/Automattic/woocommerce-payments/issues/2656

**Comment by dmallory42** [comment]
Thank you for all of the reports. I've been investigating this issue this week and will let you know when there are any resolutions or updates on this. Please keep adding any reports which look like they match the description to this issue. 🙂

**Comment by dreamtooloud** [comment]
The ticket I'm linking below is closed, but it was a merchant flagged by Woo Customer Success (who ultimately left WC Payments because of the issue). I don't have all the details since I can't access this merchant's site, but from what I see (missing Order ID in WC Pay dashboard), it could potentially be linked to this issue. : 

zd-4561910

**Comment by dreamtooloud** [comment]
I wanted to leave a note here since I was working on some research for a call with the merchant in zd-4614502 . 
I checked one of the other tickets from this issue, zd-4648135 and noticed the merchant there and the merchant in 4614502 had the `new payment experience` enabled on their site (if I have time today, will do a little bit more investigating into the other tickets mentioned). 

During the call, I had the merchant from zd-4614502 disable the new checkout experience. 

Someone from their office then placed a test order, from an incognito window, with a non-registered/non-company email (as a guest). 

 After placing the test order with the new checkout experience disabled, we noticed that the refund button appeared and the Order ID and Transaction number were showing as expected (d.pr/Xrckdj) . (_the failed payment order note can be ignored, the person doing the test transaction put the wrong information in the first time and it was unrelated)._

While this issue has been slightly more intermittent with other merchants, the merchant from zd-4614502 has not seen a refund button on 90-95% of their orders. So having it appear after disabling the new checkout experience was notable. 

We are going to wait until they get a few more orders in to see if we get consistent results with the new checkout experience disabled. 

 @dmallory42 , hopefully this is helpful information! I'll update once the merchant gets back to me with results from a few more orders.

**Comment by aheckler** [comment]
4665419-zen is also this.

**Comment by dmallory42** [comment]
Hi folks! 

Thanks again for providing links to tickets and information, it's very helpful!

Just to provide an update on this, we still don't have a fix but we have now been able to reproduce the issue, and we believe it is related to UPE orders. There is a race condition which specifically relates to UPE orders (in my case, I've only been able to reproduce it with orders that require 3D Secure card verification, but I'm uncertain whether this is a necessity for the bug to happen). 

This is why it is intermittent, and seems more prevalent in some sites than others (it's possible other plugins which slow down the site, or a slow host, for example could make it more likely to happen).

Now that we've found the problem, we will aim to land the fix in the next release of WCPay. In the meantime, I would recommend doing as @dreamtooloud suggested and asking merchants to test disabling UPE and make a test order to see if this resolves the problem as a workaround.

**Comment by shrutimoorthy** [comment]
Hi @dmallory42 , 

I have a user on 4640679-zen who has an active site with incoming orders with only WooCommerce Payments -  Credit/Debit card early access option selected. Once the user disables the early access and runs the test transaction would they be able to re-enable the early access once again?

**Comment by dmallory42** [comment]
Hi @shrutimoorthy,

> I have a user on 4640679-zen who has an active site with incoming orders with only WooCommerce Payments - Credit/Debit card early access option selected. Once the user disables the early access and runs the test transaction would they be able to re-enable the early access once again?

Currently, our recommendation for a user experiencing this issue would be to disable the Early Access, and keep it disabled as we believe this bug occurs only in the Early Access checkout experience for some users/sporadically.

We are hoping to land a fix for this issue in the next release of WCPay on 19th Jan, so once that release is out we'll add a note to the changelog about this fix and users would then be able to re-enable the Early Access checkout if they choose to.

**Comment by solstudioim** [comment]
Ticket from a WCPay Customer, 4561910-Zen, might relate to this

**Comment by dmallory42** [comment]
Hi folks,

Pleased to let you know that this issue was fixed with the release of WooCommerce Payments 3.6.0 on Wednesday.

Please advise customers who experience this issue to upgrade to the latest version of WCPay. If customers continue to experience any issue that sounds like this after upgrading, it could be worth asking them to try disabling the Early Checkout Experience. (and raise a bug with us!)

Thanks all!

**Comment by aheckler** [comment]
4737090-zen might still have this happening. Asking them to disable UPE and monitor after that.

**Comment by CircuitSetup** [comment]
I just had this happen on my site yesterday using WCPay 3.6.1, and it's unfortunately an order that I need to refund. I can't do this because the transaction is not tied to the order, and I get no refund button. 

In this case the customer previously placed an order with the same credit card (on Jan 25th, so probably using v3.6), and everything worked fine. 

Any ideas?

**Comment by billrobbins** [comment]
Hey @CircuitSetup, please open up a support ticket about this at WooCommerce.com.  We can help you get that taken care of: https://woocommerce.com/my-account/create-a-ticket/

**Comment by namiokuzono** [comment]
Reported in 5193851-zen
Context - p1651806133652119/1651805909.385329-slack-C7U3Y3VMY

**Comment by aheckler** [comment]
@namiokuzono This issue should have been fixed in WC Pay 4.1.0 I believe. I can see in the ticket the merchant is not on that version yet. Can you please ask them to update to the latest WC Pay version and see if this happens again after that?
