### ISSUE TITLE
Refine failed refund notes

### ISSUE THREAD

**Issue by jrodger** [Automattic/woocommerce-payments#601]
We have some basic handling of failed refunds added in #411.

After issuing a refund, the refund can fail at a later date. For example, the card used for the purchase could have expired. To handle this we send a refund failed webhook which adds a note to the order:

![image](https://user-images.githubusercontent.com/686419/79576651-89f50f80-80bb-11ea-999c-ad3e237ee371.png)

@RadoslavGeorgiev and @vbelolapotkov rightly pointed out that the notes don't make complete sense after a failure has occurred. We tell the merchant that the refund was successful, and then the next note says it wasn't.

There are also some questions about how we want to handle this more generally:

* Should the order status be moved back to "Processed"?
* Do we need to let WooCommerce know that the refund didn't actually happen?
* Does this happen frequently (to help us decide the priority of this issue)?
* Is there any prior art here?

**Comment by vbelolapotkov** [comment]
There are many questions on this issues we'd need to resolve first before proceed with implementation. AFAIR it's tricky one due to the async nature of refund failures and unreliable delivery of forwarded hooks, or in the case of successful refund there won't be any following hooks at all. Anyway, more in-depth exploration is necessary here.

**Comment by zmaglica** [comment]
I believe that this issue has enough context, and it can be moved from the Engineering review queue to the Ready of prioritization. If additional feedback or research is needed, the dedicated person can be assigned to this issue to perform additional research or reach out to the people who will have more context. 

This is the part of the Gamma backlog porter duty to reduce the number of the issues in the Engineering review column.

**Comment by naman03malhotra** [comment]
@htdat can you please check it and see if it is still relevant, then we can loop in product and design for the next steps.

**Comment by RadoslavGeorgiev** [comment]
I could have been fixed by https://github.com/Automattic/woocommerce-payments/pull/3965

**Comment by htdat** [comment]
> @htdat can you please check it and see if it is still relevant, then we can loop in product and design for the next steps.

I tested with the latest version 6.2.2 - [screenshot](https://github.com/Automattic/woocommerce-payments/assets/10045087/e678c9de-06f4-42b4-bafd-3ea87496873f), and notes are still the same as what James mentioned above. 

Moving this issue to "Product review" queue. 

> It could have been fixed by https://github.com/Automattic/woocommerce-payments/pull/3965

PR #3965 is to remove `WC_Order_Refund` attached to the order when a failing refund is caught up. It does not change note content.

**Comment by frosso** [comment]
Closing as obsolete. I went back through the original 2020 report and checked each concern against current `develop`, and all three are handled now.

The contradictory notes are gone: failed `refund.updated` webhooks route through `WC_Payments_Order_Service::handle_failed_refund()`, which only writes the failure note ("was unsuccessful/cancelled... <reason>"), reverts a fully-refunded order back to FAILED, deletes the orphaned `WC_Order_Refund` so WooCommerce no longer records a refund that didn't happen, and sets the refund-status metadata to FAILED. Failure reasons are now human-readable, mapped from Stripe's `failure_reason` codes (`class-refund-failure-reason.php`).

This was delivered mainly by #10677, building on #10600 and #3965. The only thing never picked up is the cross-gateway prior-art research (Square/PayPal/Amazon), but that was scoping color rather than the core ask - if product still wants it, better as a fresh, narrow issue than keeping a 2020 ticket open. I think we can close this.
