### ISSUE TITLE
WooPayments conflicting with cash on delivery at order confirmation page

### ISSUE THREAD

**Issue by joaodante** [Automattic/woocommerce-payments#7272]
### Describe the bug

WooPayments conflicting with cash on delivery at order confirmation page, showing that you paid with Credit/Debit card instead of Cash On Delivery

### To Reproduce

1.  Enable Cash On Delivery and WooPayments
2. Checkout with any product at your store, make sure to select Cash On Delivery as payment method
3. Check the Order Confirmation page, which payment method is listed there

### Actual behavior

Take a look at the screenshot below. You'll notice that if you choose Cash On Delivery as your payment method during checkout with WooPayments active, the order confirmation will show Credit/Debit card as the payment method. We understand how this can be confusing. Even though the customer didn't use a credit card, it might make some customers think they did instead of paying with cash on delivery.

### Screenshots
https://d.pr/i/KAuQLj

### Expected behavior

Order confirmation display cash on delivery as the payment method in case you paid with cash on delivery.

### Desktop (please complete the following information):

* OS: MacOS Ventura 13.5.2
* Browser: Chrome 
* Version: 116.0.5845.187

### Additional context

[Ticket](https://a8c.zendesk.com/agent/tickets/7075204)

**Comment by dsmithweb-a8c** [comment]
Hi there!

A merchant reported this same errant "Credit/Debit card" payment method appearing for orders made with the BACS gateway -- and when I tested on my test site, I got the same result. 

7081052-zen

**Comment by stuartduff** [comment]
Another report of this behaviour with Cash On Delivery. 

7070501-zen

**Comment by Thelmachido** [comment]
This was reported here as well zn- 7080251

I could reproduce this on my test site, as a workaround the user rolled back to 6.4 for me it only worked when WC was disabled.

**Comment by frosso** [comment]
Fixed by https://github.com/Automattic/woocommerce-payments/pull/7285 , will be part of the 6.5.1 release today.

**Comment by csmcneill** [comment]
Howdy @frosso and @mdmoore! 7094730-zen indicated that updating to 6.5.1 did not resolve this issue.

I haven't tried to duplicate this issue myself. Before we reopen the issue, I do want to know: if a payment is affected by this issue, will updating to 6.5.1 resolve the issue for that specific payment? Or will it only prevent the payment method title for orders placed while 6.5.1 is active?

**Comment by dsmithweb-a8c** [comment]
Can confirm the update fixed this issue for me. 

That said, I would not expect the recorded payment method on orders already placed to be changed by this fix.

**Comment by frosso** [comment]
> I do want to know: if a payment is affected by this issue, will updating to 6.5.1 resolve the issue for that specific payment? Or will it only prevent the payment method title for orders placed while 6.5.1 is active?

@csmcneill payments applied while 6.5.0 was active will not be retroactively affected by the fix. Only updating to 6.5.1 will fix the issue for future payments.
It's worth mentioning that the backend (merchant's wp-admin order page) shows the correct payment method. The issue appeared on order confirmation pages and emails.
